// Code generated by goctl. DO NOT EDIT.
package types

type UserInfoRes struct {
	UserId int `json:"userId"`
}

type UserInfoReq struct {
	UserId int    `json:"userId"`
	Name   string `json:"name"`
}

type UserInsertInfoRes struct {
	Name string `json:"name"`
}
