// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: bike.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RpcBikeServiceClient is the client API for RpcBikeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RpcBikeServiceClient interface {
	RpcGetBikeInfo(ctx context.Context, in *GetBikeInfoRes, opts ...grpc.CallOption) (*GetBikeInfoReq, error)
}

type rpcBikeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRpcBikeServiceClient(cc grpc.ClientConnInterface) RpcBikeServiceClient {
	return &rpcBikeServiceClient{cc}
}

func (c *rpcBikeServiceClient) RpcGetBikeInfo(ctx context.Context, in *GetBikeInfoRes, opts ...grpc.CallOption) (*GetBikeInfoReq, error) {
	out := new(GetBikeInfoReq)
	err := c.cc.Invoke(ctx, "/pb.RpcBikeService/RpcGetBikeInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RpcBikeServiceServer is the server API for RpcBikeService service.
// All implementations must embed UnimplementedRpcBikeServiceServer
// for forward compatibility
type RpcBikeServiceServer interface {
	RpcGetBikeInfo(context.Context, *GetBikeInfoRes) (*GetBikeInfoReq, error)
	mustEmbedUnimplementedRpcBikeServiceServer()
}

// UnimplementedRpcBikeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRpcBikeServiceServer struct {
}

func (UnimplementedRpcBikeServiceServer) RpcGetBikeInfo(context.Context, *GetBikeInfoRes) (*GetBikeInfoReq, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RpcGetBikeInfo not implemented")
}
func (UnimplementedRpcBikeServiceServer) mustEmbedUnimplementedRpcBikeServiceServer() {}

// UnsafeRpcBikeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RpcBikeServiceServer will
// result in compilation errors.
type UnsafeRpcBikeServiceServer interface {
	mustEmbedUnimplementedRpcBikeServiceServer()
}

func RegisterRpcBikeServiceServer(s grpc.ServiceRegistrar, srv RpcBikeServiceServer) {
	s.RegisterService(&RpcBikeService_ServiceDesc, srv)
}

func _RpcBikeService_RpcGetBikeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBikeInfoRes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcBikeServiceServer).RpcGetBikeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.RpcBikeService/RpcGetBikeInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcBikeServiceServer).RpcGetBikeInfo(ctx, req.(*GetBikeInfoRes))
	}
	return interceptor(ctx, in, info, handler)
}

// RpcBikeService_ServiceDesc is the grpc.ServiceDesc for RpcBikeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RpcBikeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.RpcBikeService",
	HandlerType: (*RpcBikeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RpcGetBikeInfo",
			Handler:    _RpcBikeService_RpcGetBikeInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bike.proto",
}
